from django.urls import path

from . import views

urlpatterns = [
    path("", views.report_list, name="report-list"),
    path("reports/add/", views.report_add, name="report-add"),
    path("reports/<int:pk>/", views.report_detail, name="report-detail"),
    path("reports/<int:pk>/edit/", views.report_edit, name="report-edit"),
    path("reports/<int:pk>/delete/", views.report_delete, name="report-delete"),
    path("reports/<int:pk>/answers/", views.save_answers, name="save-answers"),
    path("reports/<int:pk>/ai-summary/", views.report_ai_summary, name="report-ai-summary"),
    path("reports/<int:pk>/one-on-ones/add/", views.oneonone_add, name="oneonone-add"),
    path("one-on-ones/<int:pk>/edit/", views.oneonone_edit, name="oneonone-edit"),
    path("one-on-ones/<int:pk>/delete/", views.oneonone_delete, name="oneonone-delete"),
    path("action-items/<int:pk>/toggle/", views.action_item_toggle, name="action-item-toggle"),
    path("contacts/", views.contact_list, name="contact-list"),
    path("contacts/add/", views.contact_add, name="contact-add"),
    path("contacts/<int:pk>/edit/", views.contact_edit, name="contact-edit"),
    path("contacts/<int:pk>/delete/", views.contact_delete, name="contact-delete"),
    path("search/", views.global_search, name="global-search"),
    path("quick-notes/add/", views.quick_note_add, name="quick-note-add"),
    path("quick-notes/<int:pk>/delete/", views.quick_note_delete, name="quick-note-delete"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("ai-settings/", views.ai_settings, name="ai-settings"),
    path("backup/", views.backup_download, name="backup-download"),
    path("questions/", views.question_list, name="question-list"),
    path("questions/<int:pk>/edit/", views.question_edit, name="question-edit"),
    path("questions/<int:pk>/delete/", views.question_delete, name="question-delete"),
    path("resources/", views.resource_list, name="resource-list"),
    path("resources/add/", views.resource_add, name="resource-add"),
    path("resources/<int:pk>/", views.resource_detail, name="resource-detail"),
    path("resources/<int:pk>/edit/", views.resource_edit, name="resource-edit"),
    path("resources/<int:pk>/delete/", views.resource_delete, name="resource-delete"),
]
