# Generated by Django 4.2.30 on 2026-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='Hostname or IP, e.g. 192.168.1.50', max_length=255)),
                ('port', models.PositiveIntegerField(default=11434)),
                ('selected_model', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ollama settings',
                'verbose_name_plural': 'Ollama settings',
            },
        ),
    ]
