# Generated by Django 4.2.30 on 2026-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_ollamasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='directreport',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='directreport',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directreport',
            name='ai_talking_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='directreport',
            name='ai_talking_points_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
