# Generated by Django 4.2.30 on 2026-09-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_ollamasettings_summary_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ollamasettings',
            name='extract_action_items_prompt',
            field=models.TextField(default='You are reviewing raw notes from a 1:1 with a direct report. Identify any concrete action items, follow-ups, or commitments mentioned in the notes below - things someone said they would do, or that were agreed on as a next step.\n\nNotes:\n$notes\n\nList each action item on its own line, as plain text with no numbering, bullets, or extra commentary. If there are no action items, respond with exactly: NONE'),
        ),
    ]
