# Generated by Django 4.2.30 on 2026-09-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_ollamasettings_extract_action_items_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='directreport',
            name='personal_notes',
            field=models.TextField(blank=True, help_text="Family, interests, background — anything worth remembering that isn't a 1:1 topic."),
        ),
        migrations.AlterField(
            model_name='ollamasettings',
            name='summary_prompt',
            field=models.TextField(default="You are helping an engineering manager get up to speed on their direct report, $who.\nBelow are the direct report's profile answers, personal notes, and their currently open action items from past 1:1s.\nWrite a 1 to 3 paragraph summary covering what the manager most needs to know: this person's motivations, working style, growth areas, and anything currently outstanding. Synthesize the information rather than repeating it verbatim. Do not include a preamble or heading, just the summary.\n\nProfile Q&A:\n$qa\n\nPersonal notes:\n$personal_notes\n\nOpen action items:\n$action_items"),
        ),
        migrations.AlterField(
            model_name='ollamasettings',
            name='talking_points_prompt',
            field=models.TextField(default='You are helping an engineering manager prepare for their next 1:1 with $who.\nBased on the context below, suggest 3 to 6 specific talking points or questions the manager should bring to the conversation. Return them as a short bulleted list with no preamble or heading.\n\nProfile Q&A:\n$qa\n\nPersonal notes:\n$personal_notes\n\nOpen action items:\n$action_items\n\nNotes from recent 1:1s (most recent first):\n$notes'),
        ),
    ]
