# Generated by Django 4.2.30 on 2026-09-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_notes', to='reports.contact')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_notes', to='reports.directreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quicknote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('contact__isnull', True), ('report__isnull', False)), models.Q(('contact__isnull', False), ('report__isnull', True)), _connector='OR'), name='quicknote_exactly_one_target'),
        ),
    ]
