# Generated by Django 4.2.30 on 2026-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_quicknote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, help_text="A topic label, e.g. 'Servant Leadership' or 'Difficult Conversations'.", max_length=100)),
                ('url', models.URLField(blank=True, help_text='Link to the original source, if any.')),
                ('body', models.TextField(blank=True, help_text='Markdown supported.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
